stock:
  external:
    api:
      url: http://api.marketstack.com/v1

precious-metals:
  external:
    api:
      url: https://www.goldapi.io/api


currency:
  external:
    api:
      url: https://api.exchangeratesapi.io

bt:
  currency-converter:
    url: http://localhost:8087

